import  RPi.GPIO as GPIO
import time
import telegram
import creds


group_id = ''	#group where the bot will send the msg
bot_token = ''	#bot token generated by botfather

dev = True

open_id = 'CAACAgQAAxkBAAMMYMU096nwMPMD2hEM0FgB6rmR4KYAArAJAAJMYChS-mmgEzkQgYQfBA'	#id for sticker state open
closed_id = 'CAACAgQAAxkBAAMNYMU1O5rfDBjU2H3AD88nr-6XYtIAAvkIAAJK9SlS-CGQ3z99tHsfBA'	#id for sticker state closed

if dev:
    group_id = creds.secrets['dev']['group_id']
    bot_token = creds.secrets['dev']['bot_token']
else:
    group_id = creds.secrets['prod']['group_id']
    bot_token = creds.secrets['prod']['bot_token']

bot = telegram.Bot(token=bot_token)

def open(msg, chat_id, token=bot_token):
    bot.send_sticker(chat_id=chat_id, sticker=msg)

def closed(msg, chat_id, token=bot_token):
    bot.send_sticker(chat_id=chat_id, sticker=msg)

GPIO.setmode(GPIO.BOARD)
GPIO.setup(18, GPIO.IN,pull_up_down=GPIO.PUD_UP)

last = False

while True:
   inputValue = GPIO.input(18)
   if (inputValue == True):
       if(last != inputValue):
          open(open_id, group_id)
       last = True
   else:
       if(last != inputValue):
          closed(closed_id, group_id)
       last = False
   time.sleep(0.5)
